Not Found: /friend/test
[03/Aug/2017 06:01:03] "DELETE /friend/test HTTP/1.1" 404 2076
Not Found: /friend
[03/Aug/2017 06:01:03] "POST /friend HTTP/1.1" 404 2059
Not Found: /chat_room/test
[03/Aug/2017 06:01:04] "DELETE /chat_room/test HTTP/1.1" 404 2085
[03/Aug/2017 06:01:04] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:01:07] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:01:10] "POST /message HTTP/1.1" 200 141
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:01:01
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Not Found: /friend/test
[03/Aug/2017 06:01:25] "DELETE /friend/test HTTP/1.1" 404 2076
Not Found: /friend
[03/Aug/2017 06:01:25] "POST /friend HTTP/1.1" 404 2059
Not Found: /chat_room/test
[03/Aug/2017 06:01:25] "DELETE /chat_room/test HTTP/1.1" 404 2085
[03/Aug/2017 06:01:25] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:01:27] "GET /keyboard HTTP/1.1" 200 87
Internal Server Error: /message
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/simzi/server/views.py", line 40, in message
    data = form(request)
  File "/workspace/simzi/server/views.py", line 53, in form
    "text" : "You picked " +content_str+"("+nickname+")"+"\nRank "+ str(rank),
NameError: name 'nickname' is not defined
[03/Aug/2017 06:01:29] "POST /message HTTP/1.1" 500 68786
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:01:20
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Internal Server Error: /message
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/simzi/server/views.py", line 40, in message
    data = form(request)
  File "/workspace/simzi/server/views.py", line 53, in form
    "text" : "You picked " +content_str+"("+nickname+")"+"\nRank "+ str(rank),
NameError: name 'nickname' is not defined
[03/Aug/2017 06:01:57] "POST /message HTTP/1.1" 500 68787
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:01:52
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[03/Aug/2017 06:02:18] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:02:20] "POST /message HTTP/1.1" 200 168
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:02:14
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[03/Aug/2017 06:02:32] "GET /keyboard HTTP/1.1" 200 87
Internal Server Error: /message
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/simzi/server/views.py", line 40, in message
    data = form(request)
  File "/workspace/simzi/server/views.py", line 50, in form
    url = mamber.url
NameError: name 'mamber' is not defined
[03/Aug/2017 06:02:34] "POST /message HTTP/1.1" 500 68815
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:02:29
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[03/Aug/2017 06:02:40] "GET /keyboard HTTP/1.1" 200 87
Internal Server Error: /message
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/simzi/server/views.py", line 40, in message
    data = form(request)
  File "/workspace/simzi/server/views.py", line 50, in form
    url = mamber.url
NameError: name 'mamber' is not defined
[03/Aug/2017 06:02:42] "POST /message HTTP/1.1" 500 68816
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:02:39
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:02:56
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[03/Aug/2017 06:03:00] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:03:02] "POST /message HTTP/1.1" 200 245
[03/Aug/2017 06:03:55] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:03:57] "POST /message HTTP/1.1" 200 248
[03/Aug/2017 06:03:58] "POST /message HTTP/1.1" 200 242
[03/Aug/2017 06:04:00] "POST /message HTTP/1.1" 200 245
[03/Aug/2017 06:04:01] "POST /message HTTP/1.1" 200 178
[03/Aug/2017 06:04:04] "POST /message HTTP/1.1" 200 248
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:03:00
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:04:18
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[03/Aug/2017 06:04:32] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:04:34] "POST /message HTTP/1.1" 200 258
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:04:32
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:04:58
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Not Found: /friend/test
[03/Aug/2017 06:05:04] "DELETE /friend/test HTTP/1.1" 404 2076
Not Found: /friend
[03/Aug/2017 06:05:04] "POST /friend HTTP/1.1" 404 2059
Not Found: /chat_room/test
[03/Aug/2017 06:05:04] "DELETE /chat_room/test HTTP/1.1" 404 2085
[03/Aug/2017 06:05:04] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:05:06] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:05:08] "POST /message HTTP/1.1" 200 258
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:05:04
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:05:23
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:05:28
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4ebfa9c0d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/workspace/simzi/simzi/urls.py", line 3, in <module>
    from server import views
  File "/workspace/simzi/server/views.py", line 53
    "text" : "You picked " +member.+"("+member.nickname+")"+"\nRank "+ str(member.rank),
                                   ^
SyntaxError: invalid syntax
Performing system checks...

[03/Aug/2017 06:05:52] "GET /keyboard HTTP/1.1" 200 87
Internal Server Error: /message
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/simzi/server/views.py", line 40, in message
    data = form(request)
  File "/workspace/simzi/server/views.py", line 50, in form
    "text" : "You picked " +content_str+"("+member.nickname+")"+"\nRank "+ str(member.rank),
NameError: name 'ᅳ드ᅲᄃᄀ' is not defined
[03/Aug/2017 06:05:54] "POST /message HTTP/1.1" 500 68636
Not Found: /friend/test
[03/Aug/2017 06:05:58] "DELETE /friend/test HTTP/1.1" 404 2076
Not Found: /friend
[03/Aug/2017 06:05:58] "POST /friend HTTP/1.1" 404 2059
Not Found: /chat_room/test
[03/Aug/2017 06:05:58] "DELETE /chat_room/test HTTP/1.1" 404 2085
[03/Aug/2017 06:05:58] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:06:02] "GET /keyboard HTTP/1.1" 200 87
Internal Server Error: /message
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/simzi/server/views.py", line 40, in message
    data = form(request)
  File "/workspace/simzi/server/views.py", line 50, in form
    "text" : "You picked " +content_str+"("+member.nickname+")"+"\nRank "+ str(member.rank),
NameError: name 'ᅳ드ᅲᄃᄀ' is not defined
[03/Aug/2017 06:06:04] "POST /message HTTP/1.1" 500 68646
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:05:47
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
[03/Aug/2017 06:06:16] "GET /keyboard HTTP/1.1" 200 87
[03/Aug/2017 06:06:18] "POST /message HTTP/1.1" 200 258
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:06:10
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:06:47
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:07:03
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:07:20
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
August 03, 2017 - 06:07:28
Django version 1.11.4, using settings 'simzi.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
